development:
  adapter: postgresql
  encoding: unicode
  database: dialgus_no_tests_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dialgus_no_tests_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: dialgus_no_tests_production
  pool: 5
  username:
  password:
